export enum ChipType {
  one = 'one',
  two = 'two',
  five = 'five',
  ten = 'ten',
  twenty = 'twenty',
  twenty_five = 'twenty_five',
  fifty = 'fifty',
  one_hundred = 'one_hundred',
  five_hundred = 'five_hundred',
  one_thousand = 'one_thousand',
  ten_thousand = 'ten_thousand',
  fifty_thousand = 'fifty_thousand',
  one_hundred_thousand = 'one_hundred_thousand',
  five_hundred_thousand = 'five_hundred_thousand',
}

export enum ChipEnums {
  one = 1,
  two = 2,
  five = 5,
  ten = 10,
  twenty = 20,
  twenty_five = 25,
  fifty = 50,
  one_hundred = 100,
  five_hundred = 500,
  one_thousand = 1000,
  ten_thousand = 10000,
  fifty_thousand = 50000,
  one_hundred_thousand = 100000,
  five_hundred_thousand = 500000,
}
